server:
  servlet:
    context-path: /portal-service

token:
  timeout:
    milliseconds: 1200000 #default 600000

management:
  security:
    enabled: false
    port: 9000

init:
  data: false

report:
  subject: Novo3 Portal - School Device Order Placement report - %s
  message: Please fine the attached Order details details for %s

xero:
  update:
    toggle: false

school:
  repair:
    codes:
      BCC-NRP: BCC23
      MGS-NRP: MGS24
    covered:
      - Notebooks are covered for accidental damage.
      - Units are to be repaired/reinstated to full working order.
      - CRP covers the notebook, AC adapter and carry bag only. It does not cover any other software, peripherals or private items with the notebook.
    details:
      BCC-NRP:
        name: Ballarat Clarendon - Repair Program
      MGS-NRP:
        name: Melbourne Grammar School - Repair Program