spring.jpa.defer-datasource-initialization: true
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: always
  sql:
    init:
      data-locations: classpath:data-dev.sql
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: emailserver.temp@gmail.com
    password: znbhintpjravbmgh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

report:
  sender:
    email: emailserver.temp111@gmail.com
    name: Novo3 Portal
  receivers: madura.oneplus111@gmail.com

job:
  cron:
    expression: '0 0 8 * * *'

init:
  data: true

logging:
  level:
    com:
      novo3:
        shopfront:
          config:
            LoggingInterceptor: DEBUG
#psql "host=portal-db-svr.postgres.database.azure.com port=5432 dbname=postgres user=pirtalpgadmin password=B0lsh01B00z# sslmode=require"

#Dt$U#R&C3I%0M

#select parent_first_name, parent_last_name, email, created_on  from order_table;